"""baseline: schema inicial completo

Revision ID: 2bd03ef0fccf
Revises: 
Create Date: 2026-06-25 14:50:49.574046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd03ef0fccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('provedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('api_key_cifrada', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('unidade', sa.String(length=120), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('cor', sa.String(length=9), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('config_estrategia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escopo', sa.String(length=20), nullable=False),
    sa.Column('alvo', sa.String(length=120), nullable=True),
    sa.Column('estrategia', sa.String(length=50), nullable=False),
    sa.Column('persona', sa.String(length=120), nullable=True),
    sa.Column('camadas', sa.String(length=50), nullable=True),
    sa.Column('provedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provedor_id'], ['provedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escopo', 'alvo', name='uq_escopo_alvo')
    )
    op.create_table('papel_permissao',
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.PrimaryKeyConstraint('papel_id', 'permissao_id')
    )
    op.create_table('documento_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('oculto', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('hash_senha', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('unidade', sa.String(length=120), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('clientes', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('acesso_expira_em', sa.Date(), nullable=True),
    sa.Column('cliente_padrao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_padrao_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['papel_id'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documento_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('estrategia', sa.String(length=50), nullable=False),
    sa.Column('latencia_ms', sa.Float(), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=False),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_cliente',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'cliente_id')
    )
    op.create_table('usuario_permissao',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permissao_id')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_tecnico',
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visita_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita_tecnico')
    op.drop_table('visita')
    op.drop_table('usuario_permissao')
    op.drop_table('usuario_cliente')
    op.drop_table('notificacao')
    op.drop_table('log_consulta')
    op.drop_table('documento_tecnico')
    op.drop_table('usuario')
    op.drop_table('documento_equipamento')
    op.drop_table('papel_permissao')
    op.drop_table('config_estrategia')
    op.drop_table('cliente')
    op.drop_table('unidade')
    op.drop_table('provedor')
    op.drop_table('permissao')
    op.drop_table('papel')
    op.drop_table('feriado')
    # ### end Alembic commands ###
